Description of km_kawato_1dof
Home > kawato_1dof > km_kawato_1dof.m
km_kawato_1dof
PURPOSE
Function for computing the muscle stiffnesses for the Kawato arm model.
SYNOPSIS
function K = km_kawato_1dof(u,model) %#eml
DESCRIPTION
 Function for computing the muscle stiffnesses for the Kawato arm model.
  in:
      x      - state (pos,vel)
      u      - motor commands
      model  - model structure
  out:
      km     - muscle stiffnesses
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
k_kawato_1dof Estimate joint stiffness of 1-DOF Kawato model for a given command u and state x.
k_kawato_1dof Estimate joint stiffness of 1-DOF Kawato model for a given command u and state x.
q0_kawato_1dof Estimate equilibrium position of simplified 1-joint, 2-muscle model.
q0_kawato_1dof Estimate equilibrium position of simplified 1-joint, 2-muscle model.
tau_kawato_1dof_mx Calculate torque for Kawato 1-DOF model given state x, motor command u and model parameters (model struct).
tau_kawato_1dof_mx Calculate torque for Kawato 1-DOF model given state x, motor command u and model parameters (model struct).
SOURCE CODE
% Function for computing the muscle stiffnesses for the Kawato arm model.
%
%  in:
%      x      - state (pos,vel)
%      u      - motor commands
%      model  - model structure
%  out:
%      km     - muscle stiffnesses
%
function K = km_kawato_1dof(u,model) %#eml
N  = size(u,2);
k0 = model.k0;  % muscle stiffness parameters
gk = model.gk;  %
K  = repmat(k0,1,N) + repmat(gk,1,N).*u;
%> @file get_muscle_stiffness_kawato_1dof.m
%> @author Matthew Howard (MH), matthew.howard@ed.ac.uk
%> @date 11/07/11 17:50:47