Description of qddot_kawato_1dof
Home > kawato_1dof > qddot_kawato_1dof.m
qddot_kawato_1dof
PURPOSE
Calculate acceleration for Kawato 1-DOF model given current state x, motor command u and model parameters (model struct).
SYNOPSIS
function qddot = qddot_kawato_1dof (q, qdot, u, model)
DESCRIPTION
 Calculate acceleration for Kawato 1-DOF model given current state x, motor command u and model parameters (model struct).
  in:
     q     - joint angles
     qdot  - joint velocities
     u     - muscle activations
     model - model struct
 out:
      qddot - acceleration
CROSS-REFERENCE INFORMATION
This function calls:
tau_kawato_1dof Calculate torque for Kawato 1-DOF model given given current joint angles, velocities and muscle activations.
This function is called by:
f_kawato_1dof State space dynamics function for the 1-DOF Kawato joint (one joint, two 'kawato model' muscles).
fn_dynamics_kawato_1dof State space dynamics function for the 1-DOF Kawato joint (one joint, two 'kawato model' muscles).
SOURCE CODE
% Calculate acceleration for Kawato 1-DOF model given current state x, motor command u and model parameters (model struct).
%
%  in:
%     q     - joint angles
%     qdot  - joint velocities
%     u     - muscle activations
%     model - model struct
%
% out:
%      qddot - acceleration
%
function qddot = qddot_kawato_1dof (q, qdot, u, model)
I    = model.I; % inertia
fv   = model.viscous_friction;
tau  = tau_kawato_1dof (q, qdot, u, model); % actuator torque
qddot=(1/I)*(tau - fv*qdot);