Description of qddot_kawato_arm
Home > kawato_arm > qddot_kawato_arm.m
qddot_kawato_arm
PURPOSE
Calculate acceleration for Kawato arm model given current joint angles, velocities and muscle activations.
SYNOPSIS
function qddot = qddot_kawato_arm (q, qdot, u, model)
DESCRIPTION
 Calculate acceleration for Kawato arm model given current joint angles, velocities and muscle activations.
  in:
     q     - joint angles
     qdot  - joint velocities
     u     - muscle activations
     model - model struct
 out:
      qddot - acceleration
CROSS-REFERENCE INFORMATION
This function calls:
tau_kawato_arm Calculate torque for Kawato arm model given current joint angles, velocities and muscle activations.
qddot_planar_2_link_arm Calculate acceleration for planar 2-link arms, given a function for calculating joint torques
This function is called by:
f_kawato_arm State space dynamics function for the Kawato arm model.
SOURCE CODE
% Calculate acceleration for Kawato arm model given current joint angles, velocities and muscle activations.
%
%  in:
%     q     - joint angles
%     qdot  - joint velocities
%     u     - muscle activations
%     model - model struct
%
% out:
%      qddot - acceleration
%
function qddot = qddot_kawato_arm (q, qdot, u, model)
tau   = tau_kawato_arm (q, qdot, u, model);
qddot = qddot_planar_2_link_arm (q, qdot, tau, model);