Description of qddot_planar_2_link_arm
Home > planar_2_link_arm > qddot_planar_2_link_arm.m
qddot_planar_2_link_arm
PURPOSE
Calculate acceleration for planar 2-link arms, given a function for calculating joint torques
SYNOPSIS
function qddot = qddot_planar_2_link_arm (q, qdot, tau, model)
DESCRIPTION
 Calculate acceleration for planar 2-link arms, given a function for calculating joint torques
 in:
      q     - joint angles
      qdot  - joint velocities
      tau   - joint torques
      model - struct containing model parameters
 out:
     qddot  - acceleration
CROSS-REFERENCE INFORMATION
This function calls:
C_planar_2_link_arm Calculate Coriolis/centripetal force matrix for planar 2-link arm.
Mq_planar_2_link_arm Calculate mass matrix for planar 2-link arm.
g_planar_2_link_arm Calculate gravity force vector for planar 2-link ar given current joint angles.
This function is called by:
qddot_kawato_arm Calculate acceleration for Kawato arm model given current joint angles, velocities and muscle activations.
SOURCE CODE
% Calculate acceleration for planar 2-link arms, given a function for calculating joint torques
%
% in:
%      q     - joint angles
%      qdot  - joint velocities
%      tau   - joint torques
%      model - struct containing model parameters
%
% out:
%     qddot  - acceleration
%
function qddot = qddot_planar_2_link_arm (q, qdot, tau, model)
% mass matrix
Mq = Mq_planar_2_link_arm (q, model);
% coriolis/centripetal term
C = C_planar_2_link_arm   (q, qdot, model);
% gravity
g = g_planar_2_link_arm   (q, model);
% acceleration
qddot=Mq\(tau-C*qdot-g);
% add friction
fc = model.coulomb_friction;
fv = model.viscous_friction;
qddot = qddot - Mq\(fv*qdot + fc*sign(qdot));