Description of simulate_feedback_time_indexed
Home > simulate > simulate_feedback_time_indexed.m
simulate_feedback_time_indexed
PURPOSE
Simulate trajectory using Euler integration under closed-loop, time-indexed policy control, in continuous time
SYNOPSIS
function [x,u] = simulate_feedback_time_indexed (x0, f, pi, p)
DESCRIPTION
 Simulate trajectory using Euler integration under closed-loop, time-indexed policy control, in continuous time
 in:
    x0 - initial state
    f  - (continuous time) dynamics (function handle: xdot=f(x,u))
    pi - time-indexed policies (function handle: u=pi(x,n))
    p  - parameter struct containing:
     .N  - number of steps to simulate
     .dt - time step
 out:
     x,u     - state,action trajectory
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Test_ilqr_maccepa_contact_task Demo script: Test ilqr on reaching problem for MACCEPA actuator.
Test_ilqr_maccepa_contact_task Demo script: Test ilqr on reaching problem for MACCEPA actuator.
Test_ilqr_maccepa_contact_task Demo script: Test ilqr on reaching problem for MACCEPA actuator.
Test_ilqr_maccepa_contact_task Demo script: Test ilqr on reaching problem for MACCEPA actuator.
SOURCE CODE
% Simulate trajectory using Euler integration under closed-loop, time-indexed policy control, in continuous time
%
% in:
%    x0 - initial state
%    f  - (continuous time) dynamics (function handle: xdot=f(x,u))
%    pi - time-indexed policies (function handle: u=pi(x,n))
%    p  - parameter struct containing:
%     .N  - number of steps to simulate
%     .dt - time step
%
%
% out:
%     x,u     - state,action trajectory
%
function [x,u] = simulate_feedback_time_indexed (x0, f, pi, p)
dt= p.dt;
N = p.N;
x = nan(size(x0,1),N); x(:,1)=x0; % initialise x
u = nan(size(pi(x0,1),1),N-1);      % initialise u
% simulate
for n=1:N-1
    u(:,n  ) = pi(x(:,n),n);                 % get next action
    x(:,n+1) = x(:,n) + dt*f(x(:,n),u(:,n)); % euler step
end