Description of simulate_feedforward
Home > simulate > simulate_feedforward.m
simulate_feedforward
PURPOSE
Simulate trajectory under open-loop, feed forward control, in continuous time
SYNOPSIS
function x = simulate_feedforward (x0, f, u, p)
DESCRIPTION
 Simulate trajectory under open-loop, feed forward control, in continuous time
     x = simulate_feedforward ( x0, f, u, dt )
 in:
    x0 - initial state
    f  - (continuous time) dynamics (function handle: xdot=f(x,u))
    u  - command sequence
    p  - parameter struct containing:
         p.solver - numerical solver (see simulation_step.m)
         p.dt     - time step
 out:
    x        - state trajectory
CROSS-REFERENCE INFORMATION
This function calls:
simulate_step Make one simulation step
simulate_step Make one simulation step
This function is called by:
test_kawato_arm
maccepavd1
maccepavd1
test_maccepa
test_maccepa
SOURCE CODE
% Simulate trajectory under open-loop, feed forward control, in continuous time
%
%     x = simulate_feedforward (x0, f, u, dt)
%
% in:
%    x0 - initial state
%    f  - (continuous time) dynamics (function handle: xdot=f(x,u))
%    u  - command sequence
%    p  - parameter struct containing:
%         p.solver - numerical solver (see simulation_step.m)
%         p.dt     - time step
%
% out:
%    x        - state trajectory
%
function x = simulate_feedforward (x0, f, u, p)
N = size(u,2)+1;
x = nan(size(x0,1),N); x(:,1)=x0; % initialise x
for n=1:N-1
    x(:,n+1) = simulate_step ( f, x(:,n), u(:,n), p );
end